### PR TITLE
rpm: fix non-deterministic stability from HashMap iteration

### LINKED ISSUE #80: Non-deterministic layer packing from HashMap iteration
(Disclaimer: this bug was detected by human, and made sense of by AI)

load_from_packages iterates rpm_qa::Packages (a HashMap<String, Package>) via into_values(). Rust's HashMap uses a random seed per process, so iteration order differs between runs.

When multiple binary packages share the same SRPM, chunkah groups them into a single component. The stability value is calculated only for whichever subpackage is encountered first (the Vacant branch). Subsequent subpackages only update buildtime via max() - they do not recalculate stability.

If subpackages have different changelog_times, different iteration orders produce different stability values, which feed into the packing algorithm and produce different layer groupings. This breaks reproducibility - rebuilds of the same image can produce different layer digests.

As for why Hummingbird has subpackages with different changelog_times, I believe this is due to a bug where noarch packages are failing to be pushed to Pulp, meaning an older version of the noarch than the sRPM is present, with different releases and therefore changelogs.  This is being handled in https://github.com/konflux-ci/release-service-catalog/pull/2034.

For a reproduction test and a (hacky) fix which you probably wouldn't want as-is, please see my branch here:
https://github.com/coreos/chunkah/compare/main...p5:coreos-chunkah:dev/robertsturla/chunkah-reproducibility-issue

A failing Hummingbird reproducibility test can be found here:
https://artifacts.osci.redhat.com/testing-farm/267abb75-20f5-4610-bef5-ab82b264680f/#work-run_tests_container2i9i7wqy_ci-run_tests_container_1_default-0

---

Edit:
Talking this through with Claude, and it's not certain about the connection to the Konflux release-service-catalog bug.  But does believe the overall bug is something that should probably be handled in Chunkah.

### PR DESCRIPTION
**Pull request by jlebon**
If a rootfs has packages built from different versions of the same SRPM, (e.g. `foo-1.0-1` and `foo-libs-1.0-2`), current chunkah logic is to still put them in the same component. This seems like the right call because clearly the package set hasn't converged yet and more churn is expected.

If that does happen, we should make sure to have a deterministic stability. Right now it just depends on whichever subpackage is encountered first, which may change between invocations.

Always calculate stability, and use the lower of the two. While we're there, warn if we encounter this since it likely indicates a compose bug on the user's side.

Closes: https://github.com/coreos/chunkah/issues/80
Assisted-by: OpenCode (Claude Opus 4.6)

### CODE REVIEW

File: src/components/rpm.rs [hunk 1]
```diff
@@ -70,8 +70,20 @@ impl RpmRepo {
...
+                    let stability = calculate_stability(&pkg.changelog_times, pkg.buildtime, now)?;
+                    if stability != *existing_stability && !pkg.changelog_times.is_empty() {
+                        // Stability was derived from changelogs only and yet
+                        // they're different? That means the rootfs has RPMs
+                        // from the same SRPM and yet _different_ changelogs,
+                        // which means multiple builds of that exact SRPM NVR
+                        // were published, which is basically a compose bug.
+                        // Warn.
+                        tracing::warn!(package = %pkg.name, "package has different changelog than sibling RPM");
+                    }
```
[the remark this answers is not in the document]
Comment (jlebon) [reply src/components/rpm.rs:83]: The warning is more us trying to be nice. I don't think making sure we always emit the warning is worth adding complexity for.

File: src/components/rpm.rs [hunk 2]
```diff
@@ -65,17 +65,28 @@ impl RpmRepo {
...
                     // We want the max() of all of them as the clamp.
-                    let (existing_bt, _) = e.get_mut();
+                    let (existing_bt, existing_stability) = e.get_mut();
                     *existing_bt = (*existing_bt).max(pkg.buildtime);
+                    if stability != *existing_stability && !pkg.changelog_times.is_empty() {
+                        // Stability was derived from changelogs only and yet
+                        // they're different? That means the rootfs has RPMs
+                        // from the same SRPM and yet _different_ changelogs,
+                        // which means multiple builds of that exact SRPM NVR
+                        // were published, which is basically a compose bug.
```
Comment (p5) [inline src/components/rpm.rs]: I don't think the issue is scoped to the _same_ NVR.  Our problem also included multiple NVRs for the same SRPM was used

E.G. (totally made up examples)
- SRPM: curl-1.2.3
- Subpackage1: curl-minimal-1.2.3
- Subpackage2: curl-libs-1.2.2

Depending on whether curl-minimal or curl-libs was processed first, the packing would be different.  Now, these being different almost certainly indicates an issue in the release publishing (I'm not sure if you can pin a specific subpackage in regular usage?).

Comment (jlebon) [reply src/components/rpm.rs]: OK right. This comes from us only keeping the `name` bit from the SRPM as the component name. I do want to change that eventually I think for https://github.com/coreos/chunkah/issues/39.

Anyway, I think this patch still fixes that case as well. But I'll update the comment and commit message to be more accurate.

Comment (p5) [reply src/components/rpm.rs]: > Anyway, I think this patch still fixes that case as well. But I'll update the comment and commit message to be more accurate.

Awesome - from the diff it wasn't obvious that this covered both cases.  Just wanted to make sure you had the right context so would know if the fix was suitable.

This wasn't me nit-picking the comment string.

Thank you!

Comment (jlebon) [reply src/components/rpm.rs]: No, thanks for bringing this up. It now makes a lot more sense how this could happen. And it's important to have good comments and commit messages for both humans and future AI agents!

**Comment by jlebon** [comment]
Just going to force-merge this. CI has already passed on it and the only change is a comment string.
